{% set name = "shortid" %}
{% set version = "0.1.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/shortid-{{ version }}.tar.gz
  sha256: adaa0c51269d9b5b635eedc408672b08697d404099370ea0857d108a48eef6ac

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}

test:
  imports:
    - shortid
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/corpix/shortid
  summary: Short id generator
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
